# Generated by Django 4.2.5 on 2023-09-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_units', '0002_businessunit_sendpulse_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunit',
            name='last_update_sendpulse',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='sendpulse_token',
            field=models.CharField(blank=True, max_length=128, verbose_name='sendpulse token'),
        ),
    ]
