# Generated by Django 4.2.5 on 2023-09-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_units', '0006_alter_businessunit_last_update_sendpulse'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunit',
            name='default_text',
            field=models.CharField(blank=True, max_length=600, verbose_name='default text'),
        ),
    ]
