# Generated by Django 4.2.5 on 2023-09-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_units', '0008_businessunit_last_update_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunit',
            name='temperature',
            field=models.IntegerField(default=0, verbose_name='temperature'),
        ),
    ]
