# Generated by Django 4.2.5 on 2023-10-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_units', '0009_businessunit_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunit',
            name='max_tokens',
            field=models.IntegerField(default=0, verbose_name='max tokens'),
        ),
    ]
