# Generated by Django 4.2.5 on 2023-10-02 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_units', '0013_remove_businessunit_sendpulse_chain_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessunit',
            name='sendpulse_flow_id',
        ),
    ]
