# Generated by Django 4.2.5 on 2023-10-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_units', '0014_remove_businessunit_sendpulse_flow_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessunit',
            name='temperature',
            field=models.FloatField(default=0, verbose_name='temperature'),
        ),
    ]
