# Generated by Django 4.2.5 on 2023-10-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_units', '0019_businessunit_eval_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunit',
            name='gpt_model',
            field=models.PositiveIntegerField(choices=[(1, 'Gpt 3.5'), (2, 'Gpt 4')], default=1, verbose_name='GPT model'),
        ),
    ]
